== Selección del Diario de John Burnyeat

En el año 1653,
le plació al Señor en Su amor y misericordia enviarnos a Su fiel siervo George Fox,
y a otros de Sus fieles siervos y mensajeros del evangelio de paz y buenas nuevas.
Él estaba provisto del poder eterno de Su Palabra,
en la sabiduría y poder de la cual nos proclamó el Día del
Señor (en nuestro condado de Cumberland y norte de Inglaterra),
exponiéndole a miles que estaban equivocados y que buscaban al Señor,
el camino correcto de vida, pero que no sabían cómo encontrarlo,
ni cómo llegar a conocerlo, aunque Él no estaba lejos de nosotros.
Este bendito hombre, George Fox, uno de miles, pueden decir muchos,
y escogido antes que muchos miles, fue enviado entre nosotros en el poder del Altísimo,
lleno de la fuerza de Su Palabra.
En la sabiduría de Dios,
dirigió a miles a la luz y aparición de Jesucristo su Salvador en sus propios corazones,
para que pudieran llegar a conocerlo,
y conocer la gloria del Padre a través de Él en Su aparición,
y llegar a creer en Él con el corazón y confesarlo con la boca para salvación.

¡Bendito sea el Señor por el día de misericordia en el que Él nos visitó,
porque Le plació hacer esta obra de amor efectiva en miles,
adonde Sus siervos fueron enviados a trabajar!
Y entre estos,
le plació al Señor concederme el favor de conservar una porción de esta bendita visitación,
por medio de la cual fui informado del camino correcto
del Señor y dirigido a la verdadera luz,
hacia la que el apóstol Pablo fue enviado a volver a la
gente en su día (de las tinieblas y poder de Satanás,
a Dios y Su bendito poder), la cual, en mi espera en la luz, recibí.

A través de esta luz,
un profundo juicio brotó en mi alma y una gran aflicción creció en mi corazón,
por lo cual fui llevado a una gran tribulación y tristeza,
como nunca antes había experimentado en toda la profesión de mi religión. De hecho,
podría decir en espíritu,
que era como "`el tiempo de angustia de Jacob,`" pues el Dios del cielo,
mediante la luz de Su bendito Hijo que me alumbraba y brillaba en mi corazón,
me dejó ver el cuerpo de muerte y el poder del pecado que reinaba en mí,
y me llevó a sentir la culpa de esto sobre mi consciencia,
para que pudiera decir que Él "`me hizo cargo de los pecados de mi juventud.`"

A pesar de toda mi altiva profesión de justicia imputada, y la creencia de que,
aunque yo viviera en el acto de pecado, la culpa de este no sería cargada sobre mí,
sino imputada a Cristo y Su justicia imputada a mí;
cuando me volví a la luz encontré que era todo lo contrario,
pues esta manifestó todas las cosas reprochables.
Me di cuenta de que la culpa permanecía mientras el cuerpo de muerte permaneciera,
y mientras aún fuéramos conducidos al acto de pecado a través del poder de este.
Entonces vi que había necesidad de un salvador para salvar del poder del pecado,
así como también de la sangre de un Cristo sacrificado para borrar el pecado,
y de fe en Su nombre para la remisión de los pecados pasados.
Después de esto comenzó la lucha del verdadero esfuerzo por entrar en el reino.
Experimenté el estado de Pablo: El __querer__ estaba presente,
pero el poder para __hacer,__
muchas veces estaba ausente.
Entonces fue conocido el clamor:
"`¡Miserable de mí! ¿Quién me librará de este cuerpo de muerte?,`" y ¿quién
me librará del poder dominante de la ley que permanece en los miembros,
peleando contra la ley en mi mente y llevándome cautivo a la ley del pecado?

Cuando verdaderamente comenzó la guerra,
toda mi orgullosa presunción en mi fe inventada y conceptual,
y todas mis pretensiones y esperanzas de justificación a través de esta,
fueron derribadas.
En realidad, todo lo que yo había edificado por varios años en mi profesión,
desde los días de mi juventud (durante los cuales hubo en mí tiernos
movimientos en busca de una verdadera relación con el Señor,
conocimiento de Él y paz con Él), resultó ser nada más que una torre de Babel,
sobre la cual Dios trajo confusión. Vi que una torre así nunca
podría alcanzar el cielo por estar fuera de la fe de Su pacto,
ni podría llevar al corazón a confiar verdaderamente ni a depender de Su palabra,
sino que dirigiría a las invenciones, a la voluntad y a la acción del yo,
aunque se hablara de cosas verdaderas.

Luego, al ver todas mis obras confundidas por las visitaciones de Dios,
y por la visitación de la Aurora de lo alto que descubrió las cosas tal como eran;
y verlas a todas terminar en Babel y al Dios del cielo trayendo confusión sobre ellas,
quedé atónito y un temor me cercó por todo lado.
Por momentos empecé a temer que estaba perdido para siempre,
porque algo había entrado en mi corazón que volvió el campo fructífero en un desierto,
y lo que yo pensaba que era como el Jardín del Edén en un bosque.
El Día de Dios manifestó que todo era desolación, sequedad y muerte,
y llevó mi alma a un profundo lamento y a tristezas como nunca antes había experimentado.
Me lamenté y lloré muchas veces, y mi debilidad era tal, que deseé estar en un desierto,
donde no me encontrara con ninguna tentación o provocación externa.
Porque todas las ideas de las que hablé,
acerca de que la justicia imputada de Cristo era la mía,
no fueron confirmadas por el sello de Su Espíritu, y por tanto,
mi justicia era sólo una presunción. Vi claramente que mi
supuesta justicia era algo de mi propia invención,
y por consiguiente,
que sólo era como la hoja de higuera con la que Adán se había cubierto,
en la que no pudo soportar la llegada de Dios.

¡Oh,
la aflicción que me alcanzó! ¡La angustia que me embargó! ¡El horror
y el terror que se levantaron en mi seno! ¡La pobreza y la carencia
en que se vio mi alma por el surgimiento de la reveladora luz,
hacia la que el ojo de mi alma estaba vuelto!
Cuando esta luz se levantó, de la que los apóstoles de antaño escribieron,
lo manifestó todo; no sólo la carencia en la que yo estaba,
sino también las cosas que Dios reprobaba.
Entonces,
"`el pecado llegó a ser sobremanera pecaminoso,`" y el peso
y la carga de este llegó a ser sobremanera gravoso,
y todo el placer del mismo fue quitado de mí (y de muchos otros)
en ese día. Después de esto empezamos a llorar por un salvador,
a buscar un libertador y a rogar por un ayudador y sanador.
Porque el Día del Señor que trae desolación nos había alcanzado,
y el fuego y la espada que Cristo trae sobre la tierra
(mediante la cual quita la paz) había llegado a nosotros.
Sin embargo, nosotros realmente no conocíamos a Aquel de quien venía todo esto,
aunque Su ardor y juicio habían comenzado,
mediante lo cual la inmundicia debía ser quitada.

En esta angustia nuestros gemidos y nuestros clamores
al Señor eran profundos y llegaron ante Él,
y le agradó al Señor oír y mostrar misericordia.
Nosotros nos reuníamos con frecuencia,
tal como los mensajeros del Señor (a quienes Él había
enviado entre nosotros) nos habían exhortado hacer,
y nos manteníamos atentos a la luz de Cristo en nuestros
corazones y a cualquier cosa que ella sacara a relucir.
Y a través de la asistencia de dicha luz,
peleábamos y vigilábamos en nuestros espíritus contra el mal que se encontraba ahí,
y con el entendimiento que recibíamos,
esperábamos en el Señor para ver que más pondría Él de manifiesto,
siempre con la santa resolución de obedecer Su voluntad en la medida de nuestras posibilidades,
sin importar cuánto nos costara.

Puedo testificar que la siguiente era la condición de muchos en ese día:
Nosotros no le dábamos valor al mundo, ni a ninguna gloria o placer en este,
en comparación con la redención de nuestra alma del estado caído. Verdaderamente anhelábamos
libertad del horror y del terror que sentíamos bajo la indignación del Señor,
en la que vimos que estábamos debido a la culpa del pecado que estaba sobre nosotros.
Así que nos rendimos para soportar la indignación del Señor (porque habíamos pecado),
y nos esforzamos para esperar hasta que la indignación pasara,
y que en Su misericordia el Señor borrara la culpa
que permanecía (la que ocasionaba ira),
limpiara nuestros corazones de una mala consciencia y nos lavara con agua pura,
a fin de que pudiéramos acercarnos con un corazón sincero y en plena certidumbre de fe,
como los cristianos de antes habían hecho.
(Hebreos 10:22)

¡Pero, ay, no teníamos libertad, pues carecíamos de la fe viva!
Ni teníamos un corazón sincero mediante el cual acercarnos, y por tanto,
no podíamos tener plena certidumbre, sino que estábamos rodeados de temores,
horrores y estupor.
Sin embargo, llegamos a saber que no había otra manera, excepto morar en estos juicios,
esperar en el camino de Sus juicios (Isaías 26:8),
entendiendo que debíamos ser redimidos con juicio,
como le fue dicho a Sión. (Isaías 1:27) Así que esperando en estos,
comenzamos a aprender justicia y a desear fuertemente caminar en ella,
porque ya no estábamos satisfechos con sólo hablar de ella.
Así, pues, esperando y buscando al Señor (aunque muy ignorantes de Él),
en una profunda consciencia de nuestra propia indignidad y falta
de preparación para encontrarlo debido a la contaminación de nuestros
corazones (que fue vista por Su luz que brilló en ellos),
permanecimos postrados en espíritu, afligidos y azotados en el alma, y sin consuelo.
En realidad, nuestros corazones eran inestables como el agua,
con olas que pasaban sobre nuestras cabezas y con nuestras almas en peligro continuo.
Nuestra fe era tan pequeña, que al igual que Pedro,
con frecuencia estábamos a punto de hundirnos y clamando en el peligro.

En esta aflicción y valle de lágrimas por el que caminábamos, por un lado,
nuestros corazones quedaron como bastante muertos al mundo,
y a todos sus placeres y gloria, y por otro,
llegamos a morir a todas nuestras anteriores profesiones religiosas,
porque vimos que no había vida en ellas, ni ayuda o salvación,
aunque algunos de nosotros las habíamos probado a fondo.
Vimos que era en vano buscar salvación en esas colinas o montañas. Por tanto,
al ver el vacío de todas estas cosas,
comenzamos a abandonar lo de ambos lados--tanto la gloria, vanidad y placer del mundo,
como la imagen muerta de la profesión religiosa que habíamos
establecido en nuestras imaginaciones e invenciones,
y que habíamos adorado con nuestros corazones no enderezados y
espíritus no santificados (siendo aún esclavos y cautivos del pecado,
como todos los que obedecen sus deseos, según Romanos 6:15-16). Sí,
cuando tuvimos una verdadera visión y sentido de que todo
lo que teníamos o podíamos hacer para darnos alivio,
ayuda o salvación era insuficiente, entonces lo rechazamos.
Y tal como se nos había instruido,
volvimos nuestras mentes hacia la luz de Cristo que brillaba en nuestros corazones,
creímos en Él (según Su mandamiento, Juan 12:36) y nos reunimos para esperar en el Señor,
en la luz.

Los profesantes altivos de nuestros días desconocían al Espíritu Santo,
debido a su resistencia a Él. Ellos blasfemaban contra la vida y el poder,
y en el mejor de los casos, se alimentaban del árbol del conocimiento.
Todavía recuerdo bien, que en mi espera en el Señor,
en la profunda angustia y pesado juicio que estaban sobre mi alma,
para ver si Él aparecería,
derrumbaría y me daría alivio de lo que me mantenía sometido
como si fueran barras de hierro... Quiero decir,
recuerdo la primera efusión del poder de Dios sobre mi alma (o el primer
derramamiento del Espíritu Santo sobre mí) y cómo llegué entonces a un
verdadero descubrimiento del misterio del árbol del conocimiento.

Vi claramente en la luz,
de cuál árbol me había estado alimentando (junto
con todos los profesantes carnales de religión),
y cómo habíamos hecho una profesión de lo que no poseíamos.
En realidad, nuestras almas aún estaban muertas,
alimentándose de la mera conversación de lo que los santos de antaño disfrutaron.
Y vi que no había forma de llegar al Árbol de la Vida (para
que nuestras almas fueran sanadas por sus hojas,
se alimentaran de Su fruto y vivieran para siempre),
si yo primero no caía bajo la hiriente y asesina espada que desenvaina Cristo,
por medio de la cual es destruida la vida del viejo hombre.
Vi cuánto desea este hombre permanecer en pecado y servirlo, y aún así,
profesar fe en Cristo y declarar que es Su siervo (lo cual es imposible,
según el propio dicho de Cristo: "`Ninguno puede servir a dos señores,`" Mateo 6:24).

Quedó claramente expuesto para mí, que no había otro remedio:
Debía ser sepultado con Él para muerte por el ardiente bautismo de Cristo,
o de lo contrario, no habría resurrección con Él en novedad de vida.
Puede que haya un levantamiento en novedad de profesión religiosa, ideas y palabras,
pero eso no serviría, porque lo que yo necesitaba era novedad de vida; lo otro,
lo había intentado una y otra vez.
Vi que debía morir con Él, o ser plantado con Él en la semejanza de Su muerte--es decir,
verdaderamente morir al pecado--si alguna vez quería
ser unido con Él en la semejanza de Su resurrección,
y así vivir para Dios, según Romanos 6.

Cuando estas cosas me fueron reveladas, claramente vi que todos habíamos sido engañados,
al pensar que mientras viviéramos en la carne, según la carne, y por tanto,
en la muerte (alimentándonos del árbol del conocimiento del que estaba prohibido comer),
podríamos cosechar vida eterna.
Pues muy pronto descubrí que el hombre cosecharía según había vivido,
y según había sembrado, y no según lo que había profesado o de lo que había hablado.

Entonces estuve dispuesto a inclinarme ante la cruz
y someterme al ardiente bautismo del Espíritu,
y dejar que fuera destruido lo que debía ser consumido,
para que mi alma pudiera ser salvada, y llegara a poseer lo que dura,
permanece para siempre y no puede ser sacudido.
En consecuencia, los cielos fueron conmovidos, así como también la tierra,
para que lo inconmovible permaneciera,
de acuerdo a Hebreos 12:27. Pues la luz o el verdadero
Testigo (conforme le hacíamos caso en nuestros corazones),
condenaba los frutos malos de la carne, tanto en nuestra conducta liviana,
como en los deseos y pasiones de nuestros corazones; y además,
puso al descubierto y condenó nuestra profesión religiosa
carnal (la que estaba en esa misma naturaleza y mente),
de modo que nuestra falsa cubierta y vestimenta fueron
quitadas y nosotros quedamos sin consuelo,
desnudos, pobres y sin habitación.

Luego vimos con toda claridad,
que nuestra adoración y nuestro pecado eran similares ante los ojos de Dios.
En realidad, incluso nuestras oraciones eran rechazadas y despreciadas,
porque todas eran hechas en una naturaleza y desde una misma semilla y corazón corrupto.
Por tanto, nosotros llegamos a ser como el Judá antiguo (Isaías 1 y 66:3),
que matar un buey, sacrificar un cordero,
ofrecer una oblación y quemar incienso eran como matar a un hombre, degollar un perro,
ofrecer sangre de cerdo y bendecir un ídolo.
Así vimos, que por falta de justicia, no guardar los mandamientos del Señor,
y no abandonar nuestros propios caminos y todo lo que era malo,
nuestra religión era aborrecida por el Señor,
y que nosotros éramos rechazados en todos nuestros
hechos y dejados en desolación y esterilidad.
Porque sin importar lo que pretendiéramos, la verdad de lo dicho por Cristo permanece:
"`El buen árbol no puede dar malos frutos, ni el árbol malo dar frutos buenos;
el árbol se conoce por sus frutos.`"

Estas cosas se aclararon maravillosamente en nosotros,
y discernimos no sólo los pecados comunes,
de los que todos confiesan que son pecadores (aunque viven en ellos),
sino también la hipocresía y pecaminosidad de la religión que es
ejecutada fuera del verdadero Espíritu de gracia y vida (el cual
es la sal con la que todo sacrificio del evangelio debe ser sazonado,
de acuerdo a la figura del antiguo pacto).
En consecuencia, el Señor nos requirió retirarnos y separarnos de nuestra adoración,
y que esperáramos hasta tener nuestro corazón santificado
y el espíritu de nuestras mentes renovado,
para que pudiéramos entrar delante de Él con vasijas preparadas.
Pronto aprendimos que debe ser cierto en la sustancia, como lo era en la figura, a saber,
que todos los utensilios del tabernáculo debían ser santificados,
consagrados o dedicados.
Por lo tanto, salimos de entre todos los que decían adorar,
pero que vivían en inmundicia y abogaban por el pecado.^
footnote:[La idea dominante entre los protestantes (tanto entonces como ahora),
es que la verdadera libertad del pecado es una imposibilidad de este lado de la tumba.
Los cuáqueros se refieren a tal enseñanza como "`abogar por el pecado,`" es decir,
la enseñanza que argumenta la continuidad y dominio del pecado durante toda la vida.]

Entonces los profanos comenzaron a burlarse, mofarse y abusar de nosotros,
nuestras propias familias y viejos amigos se volvieron extraños para nosotros,
y se sentían ofendidos por nosotros.
En realidad, nos odiaban y comenzaron a hablar mal de nosotros,
y les parecía extraño que no corriéramos con ellos en el mismo desenfreno
de libertinaje como antes (1 Pedro 4:4). Los profesantes de religión,
incluso aquellos con quienes anteriormente habíamos caminado
en compañerismo en nuestra profesión sin vida,
también comenzaron a criticarnos, a denigrarnos, a hablar mal contra nosotros,
a acusarnos de error y cisma, y de separarnos de la fe.
También comenzaron a criticar la luz de Cristo, llamándola natural e insuficiente,
luz falsa y falsa guía. De esta manera, Cristo, en Su aparición espiritual fue criticado,
denigrado, insultado,
menospreciado y rechazado por los profesantes carnales del cristianismo de nuestro día,
tal como sucedió con los judíos en los días de Su aparición en
carne (quienes no podían ver hasta el final a través del velo).

En este estado débil, éramos acosados por todo lado, y muy angustiados,
sacudidos y afligidos.
Éramos como el pobre Israel, cuando el mar estaba delante de ellos y los egipcios detrás,
y su esperanza era tan pequeña que no esperaron más que la muerte.
Entonces le dijeron a Moisés: "`¿No había sepulcros en Egipto,
que nos has sacado para que muramos en el desierto?`"
(Éxodo 14:11) Así encontramos, que a través de muchas tribulaciones,
entrarían al reino todos los que se esforzaran correctamente
por entrar en él. (Hechos 14:22;
Lucas 13:24)

Pero cuando estábamos sumidos en nuestros temores,
y nuestras mentes no estaban bien familiarizadas con el verdadero esfuerzo (no del yo,
sino en la luz y Semilla de vida que prevalece),
o con la verdadera espera o quietud (separados de nuestros propios pensamientos,
voluntades y carrera que no prevalecen), el Señor nos envió a Sus siervos,
los cuales habían aprendido de Él. Ellos nos mostraron en qué debíamos esperar,
y nos orientaron en cómo mantenernos quietos (fuera de nuestros pensamientos
y esfuerzos propios) en la luz que revela todas las cosas,
y nos exhortaron a permanecer y a morar en los juicios que recibiéramos en ella.
Así, en la medida que nos volvíamos a la luz,
así nuestros entendimientos eran gradualmente informados
y obteníamos una medida de anclaje en nuestras mentes,
las que antes habían sido como un mar revuelto.
De hecho, una esperanza empezó a aparecer en nosotros,
y nos reuníamos y esperábamos para ver la salvación
de Dios (de la que nosotros sólo habíamos oído),
anhelando que Él obrara por medio de Su propio poder.

En aquellos días, aprendimos a reunirnos y a esperar juntos en silencio.
En algunas ocasiones, por meses no se pronunció ni una palabra en nuestras reuniones,
pero todo el que era fiel esperaba en la Palabra viva en su propio corazón,
a fin de experimentar santificación y una completa
limpieza y renovación de corazón y del hombre interior.
Y a medida que éramos limpiados y hechos aptos,
llegamos a tener mayor deleite en esperar en la Palabra en nuestros corazones,
para recibir la leche pura de la que habla Pedro.
(1 Pedro 2:2) Y ciertamente, en nuestra espera recibimos su virtud y crecimos,
y fuimos alimentados con la comida celestial que nutría correctamente nuestras almas.

Así llegamos a recibir más y más del Espíritu de gracia y vida de Cristo nuestro Salvador,
quien está lleno de ellas y en quien habita la plenitud.
Él nos enseñó que "`renunciando a la impiedad y a los deseos mundanos,
vivamos en este siglo sobria, justa y piadosamente.`"
Llegamos a conocer al verdadero Maestro,
Al que los santos de la antigüedad experimentaron
(como dijo el apóstol en Tito 2). Por lo tanto,
aunque habíamos dejado a los sacerdotes asalariados y también a
otros altivos "`entendidos,`" y nos sentábamos juntos en silencio,
no carecíamos de un maestro o de la verdadera instrucción divina.
Porque este era nuestro deseo:
Tener toda la carne silenciada delante del Señor y de Su poder,
tanto dentro como fuera de nosotros.
Y así, conforme entramos en el verdadero silencio y quietud interna,
empezamos a oír la voz del que dijo: "`Yo soy la resurrección y la vida.`"
En realidad, Él nos dijo: "`Vivan,`" y les dio vida a nuestras almas.
Este don santo que Él ha dado,
ha sido en nosotros como una fuente de agua que salta para vida eterna,
de acuerdo a Su promesa.
Por tanto, ha sido nuestro deleite todo el tiempo esperar en Él,
y acercarnos con nuestros espíritus a Él,
tanto en nuestras reuniones como en otros momentos,
para que podamos ser enseñados y salvados por Él.

Así, pues, por un tiempo nos reunimos de esta manera,
tan frecuentemente como encontrábamos oportunidad,
y fuimos ejercitados en los juicios vivos que brotaban en la luz en nuestras almas,
y continuamos buscando la salvación de Dios.
También buscamos al Señor con espíritus angustiados,
tanto de noche sobre nuestras camas como de día cuando estábamos
en nuestros trabajos (porque no nos podíamos detener,
pues nuestras almas estaban muy afligidas).

¡Entonces, el maravilloso poder de lo alto fue revelado entre nosotros,
y muchos corazones fueron alcanzados por él,
quebrantados y derretidos delante del Dios de toda la tierra!
Gran pavor y temblor cayó sobre muchos, y las cadenas de muerte fueron rotas por Él,
las ataduras fueron soltadas y muchas almas fueron aliviadas y puestas en libertad.
Los prisioneros de esperanza empezaron a salir y aquellos
que se habían sentado en tinieblas comenzaron a mostrarse.
Numerosas promesas del Señor, de las que habló el profeta Isaías,
se cumplieron para muchos.
Algunos experimentaron el óleo de gozo, y una alegría celestial entró en sus corazones,
y en el gozo de sus almas irrumpieron en alabanzas al Señor. Sí,
la lengua del mudo fue desatada por Cristo, el Sanador de nuestras enfermedades,
y muchos comenzaron a hablar y a anunciar las maravillas de Dios.

Grande fue el pavor y la gloria de ese poder,
el cual en una reunión tras otra era misericordiosa y ricamente manifestado entre nosotros,
quebrantando,
suavizando y derritiendo nuestras almas y espíritus delante del Señor. Luego,
nuestros corazones comenzaron a deleitarse en el Señor y
en Su camino (el cual Él había allanado delante de nosotros),
y con gran fervor y celo empezamos a buscarlo y a reunirnos más a menudo que antes.
Nuestros corazones fueron verdaderamente afectados con la presencia de ese bendito poder,
el cual diariamente brotaba entre nosotros en nuestras reuniones,
y por medio de él éramos grandemente consolados, fortalecidos y edificados.
Porque este era el mismo Consolador que nuestro Señor había prometido enviar del Padre.
(Juan 14:26-27: Juan 16:13-15) Y este Consolador,
habiendo venido y habiendo sido recibido, nos enseñaba a conocer al Padre y al Hijo.
Sí, conforme lo fuimos conociendo y entrando en la unidad de Él, fuimos enseñados por Él;
fuimos enseñados por el Señor de acuerdo a la promesa del nuevo pacto:
"`Todos tus hijos serán enseñados por Jehová.`" (Isaías 54:13; 1 Juan 2:27)

Entonces nuestros corazones se inclinaron a escuchar al Señor,
y nuestros oídos (los cuales Él había abierto para
que oyeran) a oír la enseñanza del Espíritu.
En realidad,
oímos lo que Él le dijo a la iglesia y vimos que
Él era el principal Pastor y Obispo de nuestras almas,
quien nos llevaba a la práctica correcta del evangelio
y a la verdadera adoración del evangelio.
Por medio de Su nombre recibimos la remisión de los pecados pasados,
y por medio de Su sangre nuestros corazones fueron purificados de mala consciencia y
se nos dio el agua pura que nos lavó y nos limpió. De modo que con corazones sinceros,
muchos comenzaron a acercarse al Señor en plena certidumbre de fe,
como los santos de antaño habían hecho, y fueron aceptados.
Encontramos entrada por ese mismo Espíritu;
por ese mismo Espíritu fuimos bautizados en un solo cuerpo,
se nos dio a beber de un mismo Espíritu, y por tanto, fuimos refrescados,
muy consolados y crecimos juntos en el misterio de la comunión del evangelio.
Así adoramos a Dios, quien es Espíritu,
en el Espíritu recibido de Él (la cual es la adoración del evangelio,
de acuerdo a lo dicho por Cristo en Juan 4:24).

Luego vimos aún más claramente,
que en general todas las adoraciones en el mundo estaban
establecidas por imitación o invención del hombre.
Vimos que era en vano adorar a Dios en una forma de adoración inventada o tradicional,
y enseñar como doctrinas los mandamientos de hombres (como había dicho nuestro Señor,
Mateo 15:9; Isaías 29:13). Por lo tanto,
fuimos constreñidos no sólo a retirarnos de ellos,
sino (muchos de nosotros) a ir y dar testimonio contra toda
adoración que no tuviera la vida y poder de Dios.

En consecuencia,
habiendo sido reunidos por el Señor Jesucristo (el gran Pastor de nuestras almas),
nos convertimos en Sus ovejas y aprendimos a conocer Su voz y a seguirlo.
Él nos instruyó y nos guió a delicados pastos,
donde nos alimentamos y juntos reposamos con gran deleite.
Él nos dio vida eterna y manifestó las riquezas de Su gracia en nuestros corazones,
mediante la cual fuimos salvos por la fe y libres de la ira,
el miedo y el terror que habían permanecido pesadamente sobre nuestras almas.
En verdad, llegamos a participar de esa vida en la que consiste la bendición,
y así fuimos liberados del poder de esa muerte que había reinado
y había hecho de nosotros unos miserables y desdichados.

¡Oh, el gozo,
el placer y el gran deleite con los que nuestros corazones
fueron vencidos muchas veces en nuestras reverentes y santas
asambleas! ¡Cómo se derretían nuestros corazones como cera,
cómo se derramaban nuestras almas como agua delante del Señor,
cómo se ofrecían nuestros espíritus al Señor como dulce aceite de unción,
incienso y mirra, cuando ni una sola palabra se pronunciaba en toda nuestra asamblea!
Entonces el Señor se deleitaba en descender a Su jardín
y caminar en medio de las eras de especias aromáticas.
Sí,
Él hizo '`que los vientos del norte se levantaran y que los vientos del
sur soplaran sobre Su jardín,`' y que las lluvias placenteras descendieran
para el refrescamiento de Sus plantas tiernas y para que pudieran crecer
más y más. Para aquellos que habían experimentado la noche de lloro,
ahora había llegado la mañana de alegría (de acuerdo a la antigua experiencia de David,
Salmo 30:5). Y aquellos que anteriormente habían pasado a través de profundas aflicciones,
azotes y angustias, experimentaron el cumplimiento de esa gran promesa del evangelio:

[quote.scripture, , Isaías. 54:11-14 LBLA]
____
Oh afligida, azotada por la tempestad, sin consuelo,
yo asentaré tus piedras en antimonio, tus cimientos en zafiros.
Haré tus almenas de rubíes, tus puertas de cristal, y todo tu muro de piedras preciosas.
Todos tus hijos serán enseñados por el Señor, y grande será el bienestar de tus hijos.
En justicia serás establecida.
Estarás lejos de la opresión, pues no temerás, y del terror, pues no se acercará a ti.
____

Como resultado de esto,
llegamos a ser reunidos en pacto con Dios y a experimentar
en Cristo el cumplimiento de las promesas de Dios,
en Quien todas las promesas son "`sí,
y amén.`" Nos sentamos juntos en lugares celestiales con Él,
y nos alimentamos con la comida celestial, el pan de vida que descendió del cielo,
el que Cristo (el Pastor celestial) nos dio.
Pues Él nos sacó de debajo de aquellos pastores que se alimentaban
a sí mismos con cosas temporales del rebaño,
y no sabían cómo alimentar al rebaño con comida espiritual, pues no la tenían.

Así conocimos el poder del Señor Jesucristo en nuestros corazones,
llegamos a amarlo profundamente y nos deleitamos en el disfrute
de él. Estimamos todas las cosas como escoria y estiércol
en comparación con la excelencia que encontramos aquí,
y por tanto,
estuvimos dispuestos a sufrir la pérdida de todo con tal de ganarlo a
Él (tal como sucedió con el apóstol de antaño). Bendito sea el Señor,
porque muchos obtuvieron su deseo, hallaron a su Amado y se encontraron con su Salvador,
y de este modo, experimentaron Su salud salvadora,
por medio de la cual sus almas fueron sanadas.
De esta manera llegamos a ser Su rebaño y familia, o Su familia de fe.
Como Sus hijos y bendita familia, continuamos reuniéndonos dos veces o más por semana,
y estando reunidos en Su nombre y santo temor,
experimentábamos Su promesa (de acuerdo a Mateo 18:20),
de que Él estaría en medio de nosotros,
honrando nuestras asambleas con Su poder y presencia celestiales.
Este era nuestro gran deleite,
y la dulzura de Su presencia constreñía maravillosamente nuestras
almas a amarlo y nuestros corazones a esperar en Él;
pues descubrimos que la antigua experiencia de la Iglesia era cierta:
"`Tus ungüentos tienen olor agradable, Tu nombre es como ungüento purificado;
por eso te aman las doncellas.`"

Al crecer en esta experiencia de bondad del Señor, y de dulzura,
gloria y excelencia de Su poder en nuestras asambleas,
crecimos más y más en fuerza y en celo por nuestras reuniones,
y valoramos el beneficio de ellas más que cualquier otra ganancia mundana.
Sí, estos tiempos fueron para algunos de nosotros más que nuestros alimentos esenciales.
Continuando así,
crecimos más en el entendimiento de las cosas divinas y de los misterios celestiales,
por medio de las revelaciones del poder que estaba diariamente entre nosotros,
y que obraba dulcemente en nuestros corazones,
uniéndonos más a Dios y tejiéndonos en el perfecto vínculo
de amor y comunión. Así llegamos a ser un cuerpo unido,
formado de muchos miembros, del que Cristo mismo se convirtió en la Cabeza.
Él verdaderamente estaba con nosotros y gobernaba sobre nosotros, y además,
nos dio dones,
por medio de los que crecimos en capacidad y entendimiento
para responder al fin por el que Él nos había levantado,
bendecido y santificado a través de Su Palabra, la cual habitaba en nuestras almas.

En la medida que nos aferramos a nuestro primer amor y continuamos con nuestras reuniones,
sin dejar de congregarnos (como era la costumbre de algunos en la antigüedad,
cuyo ejemplo el apóstol exhortó a los santos no seguir),
el poder del Señor continuó con nosotros.
Muchos, a través del favor de Dios, crecieron en sus dones,
sus bocas fueron abiertas y se convirtieron en instrumentos en
la mano del Señor para dar testimonio al mundo del Día del Señor,
el cual había irrumpido de nuevo, es decir,
del Día grande y notable que Joel había profetizado y del que Pedro dio testimonio.
Algunos también fueron enviados a dar testimonio contra el mundo y sus malos hechos,
y contra todas las falsas religiones con las que la humanidad se había
cubierto en la oscuridad y apostasía que se había esparcido sobre ellos,
pero que ahora era vista y puesta al descubierto por la luz y Día de Dios.

Así creció la Verdad y así también los fieles en ella, y muchos fueron vueltos a Dios.
Su nombre, fama, gloria y poder se esparcieron al exterior,
y los enemigos de la obra y reino fueron descubiertos
y heridos por el Cordero y Sus seguidores.
Esto hizo que el enemigo comenzara a enfurecerse y a mover
sus instrumentos para oponerse a la obra del Señor,
e impedir con toda su sutileza que las personas siguieran
al Cordero o creyeran en Su luz.

A partir de ese momento con pluma, lengua y manos también,
la bestia y sus seguidores comenzaron la guerra.
Recurrieron a la flagelación, azote, encarcelamiento y confiscación de propiedad.
Criticaron, se opusieron y calumniaron el camino de la verdad,
haciendo cualquier cosa que pudiera obstaculizar la exaltación del reino del Señor Jesucristo.
Blasfemaron contra Su luz y Su poder, llamando Su luz "`natural,
insuficiente y falsa guía,`" y muchos otros nombres llenos de crítica.
Llamaron Su poder y operación "`demoníaco,`" el poder que en verdad
obraba en muchos para la renovación del espíritu de la mente,
y para la reforma de la conducta de todo libertinaje, maldad,
injusticia y brujería. Estos eran como los fariseos antiguos que dijeron de Cristo,
"`Por el príncipe de los demonios echa fuera los demonios.`"

No obstante, por este tiempo,
aquellos que se habían mantenido fieles al Señor (y a Su luz y Espíritu en sus corazones),
y habían salido a través de profunda tribulación (como se relató antes),
ya habían sido confirmados, colocados,
satisfechos y establecidos en la vida que era manifestada.
En esta vida ellos vieron por encima de la muerte
y a través de las profesiones de los hombres,
y pudieron discernir dónde estaban los hombres y de qué se alimentaban.
Vieron que los que clamaban contra la luz y el poder de Cristo,
eran como los que se burlaban en el capítulo 2 de Hechos,
que pensaban que los apóstoles estaban ebrios con vino nuevo.

Desde el año 1653 (el año que fui convencido de la bendita
verdad y del camino de vida eterna) hasta el año 1657,
no me sentí impulsado a viajar mucho al extranjero para efectos de la Verdad,
salvo para visitar a los Amigos que estaban prisioneros por el testimonio de la misma.
Durante ese tiempo estuve principalmente en casa,
siguiendo mi vocación. Yo era muy diligente en mantenerme en nuestras reuniones,
al estar rendido en mi corazón a asistir fielmente; en realidad,
encontraba gran deleite en ellas.
Muchas veces,
cuando una reunión terminaba y yo estaba en mi labor
externa (en la que también era muy diligente),
anhelaba en mi espíritu el próximo día de reunión,
para poder encontrarme con el resto del pueblo de Señor
y esperar en Él. También puedo decir con seguridad,
que cuando estaba reunido no era perezoso,
sino que con verdadera diligencia ponía mi corazón a esperar en
el Señor una visitación de Él por medio de Su poder en mi alma.
Y puedo decir esto por el Señor y en Su nombre (con muchos otros testigos),
que mientras esperamos con diligencia, paciencia y fe, no esperamos en vano.
Él no dejó que nuestras expectativas fallaran.
¡Eterna gloria,
honor y alabanza sean a Su nombre digno y honorable para
siempre! ¡El solo recuerdo de Su bondad y glorioso poder,
revelado y renovado en aquellos días, conmueven mi alma!

Así, en diligente espera,
en Su misericordia el Señor visitó nuestros corazones mediante Su poder,
y mi alma era cada día más y más tocada con la gloria, excelencia y dulzura de este,
y con el temor santo que llenaba mi corazón. Esto llegó a ser placentero para mí,
por lo que mi espíritu se inclinó para mantenerse cerca de ese
poder y para morar en ese santo temor que el Padre había colocado
en mi corazón. Vi lo que David exhortó en el Salmo 2,
cuando dijo de los reyes y jueces de la tierra: "`Y ahora, reyes, entended:
admitid corrección, jueces de la tierra,`" y añadió: "`Servid al Señor con temor,
y alegraos con temblor.`"
¡Oh, las humillaciones de mi alma! ¡Oh,
el agradable temor que habitaba en mi espíritu y
los reverentes temblores que venían sobre mi corazón,
que lo llenaban con gozo vivo, como con tuétano y grosura!
Entonces podía decir en mi corazón con David: "`Lavaré en inocencia mis manos,
y andaré alrededor de tu altar, oh Señor.`" ¡Oh,
cuán agradable es acercarse al altar del Señor, teniendo corazones enderezados y llenos,
y almas y espíritus ungidos con la verdadera unción del Santo,
de la que habla Juan! (1 Juan 2:27) Esta unción es
la sustancia de la figura en Éxodo 30:25,
con la que se le ordenó a Moisés ungir todos los utensilios del tabernáculo.

De esta manera fueron adecuados,
llenados y equipados nuestros corazones muchas veces en nuestras asambleas santas,
cuando nos sentábamos juntos bajo el mismo temor y poder,
porque el templo o tabernáculo en el que adorábamos como hijos de la nueva Jerusalén,
era uno, como dice Juan, "`el Señor Dios Todopoderoso es el templo de ella,
y el Cordero`" (Apocalipsis 21:22). Y cuando mi corazón fue así acondicionado y llenado,
me esforcé por mantener mi espíritu humillado ante el sentido fundidor del poder,
y grande era el cuidado de mi alma para no perder
o abusar de ninguna manera de dicho poder,
o dejar que se levantara algo malo en mi mente y ser así traicionado por ello.
Descubrí que si yo era cuidadoso en mantener sujeto todo lo que estaba equivocado,
crecía en sana sabiduría y verdadero entendimiento,
incluso de aquellos misterios de los que el mundo era ignorante.
Porque el Hijo de Dios había llegado y fue Él quien dio "`entendimiento
para conocer al que es verdadero`" (como había dicho Juan),
y el que "`nos ha sido hecho por Dios sabiduría,`" (como dijo Pablo en
1 Corintios 1:30). Yo a menudo observaba con gran cuidado y diligencia
cómo estaba mi propio espíritu en aquellas benditas y agradables épocas
en las que el Señor aparecía maravillosamente entre nosotros,
llenando nuestros corazones de la gloriosa majestad de Su poder.
Me mantenía vigilante para ver si mi espíritu estaba sujeto a Él, como debía ser,
porque yo claramente sabía que el enemigo podía engañar y conducir a la altivez,
orgullo y vanagloria.
Porque si el alma no es mantenida humilde, pronto se vería privada del poder,
pues Él "`encaminará a los humildes por el juicio, y enseñará a los mansos su carrera.`"

En consecuencia, aún en los mayores placeres,
vi que había una constante necesidad de cuidado y temor.
Pues aquellos que crecieron perezosos,
ociosos y descuidados en la espera del poder en una reunión,
se sentaron sin el sentido de este en un estado muerto, seco y estéril.
Estos no fueron diligentes en mantenerse bajos, humildes y tiernos, y de esta manera,
ocuparse de la naturaleza del funcionamiento del poder,
y del estado de sus propios espíritus,
y también de vigilar contra las sutilezas del enemigo
(quien está esperando listo para traicionar).
De hecho, estos fueron fácilmente apartados (fuera del camino del poder) por el extraño,
incluso cuando el poder estaba operando y el gozo
estaba en los corazones de los demás. Descubrí,
que por falta del verdadero temor y cuidado,
el alma podía perderse antes de darse cuenta.
Creo que algunos han caído aquí y que difícilmente pueden encontrar la razón de ello.

¡Oh, realmente se puede decir: "`Grande es el misterio de la piedad,`" es decir,
el gran misterio del que Pablo escribe en Colosenses:
"`Cristo en vosotros la esperanza de gloria`"! Cuando Él está ahí (en nosotros),
grande es el misterio de Su operación en nosotros por medio de Su Espíritu,
para abrir y aclarar el entendimiento de todos los que esperan correctamente
en Él. Pues _el alma_ del hombre es la que experimenta la santificación,
la unidad con la vida y la verdadera unción. En efecto,
el alma es la que llega a ser un sacerdote del sacerdocio real,
escogido y elegido en el pacto de Dios,
y llega a comer correcta y lícitamente las cosas santas,
y a participar de la santa comida santificada.
Por lo tanto, el extraño no debe acercarse a este lugar,
y esto estaba representado en la figura: "`Esta es la ordenanza de la pascua;
ningún extraño comerá de ella`" (Éxodo 12:43),
ni "`Ningún extraño comerá cosa sagrada`" (Levítico 22:10), y de nuevo, Salomón dijo:
"`El corazón conoce la amargura de su alma;
y extraño no se entremeterá en su alegría`" (Proverbios 14:10). Podría decirse mucho más,
pero este es el punto del asunto:
El corazón que ha experimentado su propia amargura en juicio y angustia,
y a través de esto ha llegado a la paz y a la alegría,
debe mantenerse ahí y no dejar que lo que no tiene
participación en ello se entrometa con la alegría,
porque si lo hace, pronto derrocará la alegría del alma y la llevará a otro estado.
Entonces,
el alma no encontrará más piedad en el día de la
angustia de la que obtuvo Judas de los judíos,
después de haber traicionado a su Maestro, cuando le dijeron:
"`¿Qué nos importa a nosotros?
¡Allá tú!`"

Como he dicho antes,
continué por cuatro años principalmente siguiendo mi vocación externa,
y asistiendo y esperando en el Señor en las operaciones de Su santo poder en mi corazón,
tanto en las reuniones como en otros momentos.
Descubrí que cuando mi corazón se mantenía cerca del poder,
dondequiera que estuviera o haciendo lo que tuviera que hacer, me mantenía tierno,
suave y vivo.
Además de esto, descubrí que cuando me mantenía diligentemente vuelto hacia él,
había una constante y dulce corriente de paz,
placer y gozo divinos que corría suavemente en mi alma,
lo cual excedía por mucho los demás deleites y satisfacciones.
Esto llegó a ser una gran motivación en mi alma para velar con diligencia,
porque me di cuenta de que el amor de Dios me constreñía. Asimismo,
observé que si lo descuidaba o dejaba que mi mente
siguiera cualquier cosa más de lo que debía,
y por tanto, olvidaba esto, yo comenzaba a ser como un extraño,
y vi que pronto podría perder mi interés por estas riquezas y tesoros,
y por la verdadera herencia del Israel espiritual de Dios,
la cual Cristo había comprado para mí y me había dado el gusto de heredar.

Así continué en la santa comunión del evangelio de vida y salvación,
con el resto de mis hermanos y hermanas,
y juntos experimentamos muchos días gozosos en el poder del Espíritu Santo,
el cual rica y misericordiosamente continuaba entre
nosotros y era diariamente derramado sobre nosotros.
Continuamos creciendo en el favor de Dios y en unidad los unos con los otros,
y recibiendo cada día fuerza del Señor y un incremento de Su divina sabiduría y Espíritu,
el cual nos consolaba en gran medida.
Recuerdo bien cuán satisfecho estaba mi corazón en este
estado placentero y cómo fui cimentado en contentamiento,
en el cual estuve dispuesto a permanecer.
Y debido a las bendiciones y ricas misericordias del Señor que mi alma disfrutaba,
me dispuse a servirle en todo lo que pudiera y de buena
gana recibí una parte de Su preocupación por la iglesia,
para poder ser útil en todas las cosas necesarias.

De esta manera el Señor comenzó a moverse en mi corazón por medio de Su Espíritu,
para levantarse y salir con la fuerza de Su palabra, y declarar contra los asalariados^
footnote:[Los sacerdotes contratados.]
que se alimentaban a sí mismos y no alimentaban al pueblo,
y mantenían al pueblo ignorante de estas cosas buenas.
Pero cuando la palabra del Señor vino a mí con un mensaje para que lo declarara,
esto se convirtió en una gran prueba para mí y de buena gana la habría evitado,
y en su lugar, habría continuado en esa tranquilidad,
paz y placer al que el Señor me había llevado.
Pero pronto llegué a saber que no tendría paz sino en la obediencia al Señor y rindiéndome
para hacer Su voluntad (pues estaba seguro que era la palabra del Señor).
Entonces cedí en espíritu y comencé a anhelar el día en que yo pudiera desahogarme
y ser aliviado de la carga que estaba sobre mí. En realidad no podía contenerme,
porque el temor y la majestad del poder de la vida
que habitaba y quemaba como fuego en mi corazón,
eran de gran peso.

Cuando llegó el primer día de la semana,
fui movido por el Espíritu del Señor a ir a Lorton
y hablar con un sacerdote llamado Fogoe,
quien le predicaba al pueblo en la casa de adoración de ellos.
Me quedé hasta que terminó y lo oí afirmar en su predicación,
que tanto él como ellos estaban sin la vida de la ley y del evangelio.
Entonces hablé con él y le dije: "`¿Con qué predicas u oras,
dado que no tienes la vida de la ley ni la del evangelio?`"
Pero después de unas pocas palabras se enfureció y provocó a la gente,
entonces cayeron sobre mí, me sacaron de la casa y me golpearon,
y el sacerdote me amenazó con ponerme en el cepo.

Dos semanas después de esto,
fui movido a ir de nuevo y hablarle al mismo sacerdote en Loweswater,
la parroquia donde yo vivía entonces.
Cuando entré la gente comenzó a mirarme y a fijarse en mí,
pero el sacerdote les mandó que me dejaran en paz,
y dijo que si yo permanecía en silencio él conversaría conmigo cuando hubiera terminado.
Por tanto, me quedé quieto y callado,
esperando en el Señor. El sacerdote se preparó para ir a orar,
pero cuando vio que yo no me quitaba el sombrero (porque
no podía unirme con él en sus oraciones muertas y sin vida),
en lugar de ir a orar,
se puso a insultarme y me dijo que yo no debía permanecer ahí en esa postura.
Al final hablé con él y le pregunté de nuevo: "`¿Con qué oras,
dado que dices que no tienes la vida de la ley ni del evangelio?`";
pero él siguió llamando a la gente para que me sacara.
Al fin,
mi padre (que estaba presente y disgustado conmigo por molestar
a su ministro) vino y me sacó de la casa,
y estaba muy enojado conmigo.
Yo me quedé en el cementerio hasta que el sacerdote y la gente salieron,
y entonces me acerqué adonde él y le hablé de nuevo,
pero pronto comenzó a enfurecerse y amenazarme con el cepo,
y luego se escapó. Entonces descargué mi consciencia
de lo que tenía que decir ante la gente,
y así me fui en gran paz con el Señor.

No mucho después, el mismo año,
fui movido por el Señor por medio de Su Espíritu a ir a
Brigham y hablarle a un sacerdote llamado Denton.
Él le estaba predicando al pueblo en la '`casa del campanario,`'^
footnote:[Sabiendo que la verdadera iglesia es el cuerpo espiritual de Jesucristo,
los primeros cuáqueros no estaban dispuestos a usar el término
"`iglesia`" para referirse al edificio físico,
y en su lugar usaban el término en inglés "`steeple-house,`"
el cual significa '`casa del campanario.`']
y su sermón (el cual él había preparado de antemano) tenía muchas acusaciones falsas,
mentiras y calumnias contra los Amigos y contra los principios de la verdad.
Yo me quedé hasta que él terminó y luego le hablé,
pero recibí poca respuesta antes de que algunos de sus oyentes cayeran sobre mí,
me golpearan con sus biblias y con sus bastones continuamente,
mientras me sacaban de la casa y también del cementerio,
de modo que al día siguiente estaba dolorido por los golpes.
Luego el sacerdote mandó al aguacil a detenerme, a mí y a un Amigo que estaba conmigo.
Así, al día siguiente, fuimos llevados a Lancelot Fletcher de Tallentire,
quien mandó que se escribiera una orden de arresto contra nosotros,
y fuimos enviados de alguacil a alguacil y luego a la cárcel común en Carlisle,
donde estuve prisionero por veintitrés semanas.

Mientras estaba en prisión, una carga por Escocia vino sobre mí,
pero estando prisionero y no muy familiarizado con la manera y la obra
del poder y Espíritu del Señor en relación a este tipo de servicio,
el ejercicio bajo el cual estaba mi espíritu era grande.
Pues fui abrumado por falta de experiencia y claridad de entendimiento,
y por un tiempo estuve bastante perdido en lo profundo,
donde la angustia de mi alma estaba más allá de las palabras.
Pero el Dios misericordioso,
mediante Su poderoso brazo y sanadora y salvadora Palabra de vida,
restauró y sacó mi alma de las profundidades donde estuvo sepultada por un tiempo.
En realidad, Él renovó la vida y la comprensión,
e hizo que la luz de Su rostro brillara y que la dulzura de Su paz brotara,
para que yo en verdad pudiera decir:
"`Él hizo que los huesos que Él había quebrantado se regocijaran.`"
Cuando Él me había quebrantado y humillado,
y me había dejado ver cómo podía hacer que todas las cosas se convirtieran en nada,
y así esconder toda la gloria del hombre, entonces, en Su bondad reveló Su propia gloria,
poder, presencia y vida vigorizante.
Sí, Él le reveló a mi entendimiento Su buena voluntad,
de tal manera que me rendí voluntariamente en corazón y espíritu,
con toda prontitud y complacencia de mente.

Después de permanecer cerca de veintitrés semanas en prisión, me dieron mi libertad,
regresé a casa y seguí con mi vocación externa ese verano.
Crecí más en la comprensión de la mente y voluntad del Señor,
con respecto a aquellas cosas que yo tuve a la vista mientras
estaba en prisión. Me mantuve en las reuniones y continué
esperando en el Señor en un verdadero esfuerzo de espíritu,
para conocerlo más y disfrutar más de Su poder y Palabra.
Así crecí no sólo en entendimiento, sino también en un grado de fuerza y capacidad,
para responder al servicio que el Señor me había llamado.

Entonces, en la fe que descansa en el poder de Dios,
hacia el principio del octavo mes de 1658, hice mi viaje a Escocia;
viajé en esa nación por aproximadamente tres meses.
Estuve tanto en el norte como en el oeste de ese país;
tan al norte como Aberdeen y de regreso a Edinburgh, y al oeste en Linlithgow, Hamilton,
Ayr, hasta Port Patrick y de regreso a Ayr y Douglass.
Hacíamos nuestro servicio en sus '`casas de campanario,`'
sus mercados y otros lugares donde nos reuníamos con personas,
y a veces en reuniones de Amigos, dondequiera que hubiera alguna.
Nuestra obra era llamar a las personas al arrepentimiento,
a salir de su profesión hipócrita sin vida y de las formalidades muertas (en
las que se habían establecido en la ignorancia del Dios vivo y verdadero),
y volverlos a la verdadera luz de Jesucristo en sus corazones,
para que ahí pudieran llegar a conocer el poder de Dios, y de esa manera,
experimentar la remisión de pecados y recibir herencia entre los santificados.
Sintiéndonos aliviados de la carga con respecto a esa nación,
regresamos a Inglaterra y llegamos por agua a Bowstead
Hill el primer día del mes once de 1658.

Después de mi regreso a casa,
seguí con mi oficio nuevamente y me mantuve en las reuniones hasta el tercer mes de 1659,
después del cual tomé un barco hacia Irlanda.
Porque mientras estuve en Escocia,
nació en mí una preocupación en la verdad por visitar esa nación,
y mientras estaba en casa,
creció poderosamente en mí a través de la fuerza de la Palabra de vida.
Pues el Señor con frecuencia llenaba y enriquecía
mi corazón y mi alma con Su glorioso poder,
y así me santificaba y me preparaba para lo que disponía
para mí. A menudo fui llevado a Irlanda en espíritu,
y tenía fijo en mí que esa nación era el lugar donde debía ir para servirle al Señor,
dar testimonio de la Verdad,
llamar a la gente al arrepentimiento y exponer el camino de vida y salvación para ellos.

Esperé hasta que se cumpliera el tiempo (de acuerdo al bendito consejo de Dios,
en el que encontré Su poder de guía conmigo, y también yendo antes que yo),
y en el momento antes mencionado,
tomé el barco en Whitehaven y toqué tierra en Donaghadee al norte de Irlanda.
Viajé a Lisburn, Lurgan y a Kilmore en el condado de Armagh; y así,
por algún tiempo tuve reuniones entre Amigos de arriba abajo en el norte.
Mucha gente llegó a las reuniones,
y muchas de ellas fueron convencidas y vueltas a
Dios del mal y de la vanidad de sus caminos.
De ahí viajé a Dublin y luego a Mountmellick, y así sucesivamente a Kilkenny, Caperqueen,
Tullow, Cork y Bandon, y de regreso a Cork y luego a Youghal, Waterford, Ross y Wexford.
Tuve reuniones a lo largo del camino mientras viajaba,
y de acuerdo a la capacidad que recibí de Dios,
fue fiel y prediqué la verdad y de la verdadera fe de Jesucristo.

Habiendo atravesado el país y publicado el nombre
y la verdad de Dios en Su temor cuando tenía oportunidad,
me dispuse a regresar a mi hogar en Inglaterra.
Para ese propósito bajé a Carrickfergus, pero antes de llegar,
vino sobre mí que debía regresar a Lurgan y Kilmore, y de ahí a Londonderry.
Así que mandé un mensaje para que convocaran una reunión en Lurgan y continué a Carrickfergus,
donde tuvimos una reunión a la que asistieron muchas personas.
Allí descargué lo que había en mi consciencia para ellos en el temor del Señor,
y luego regresé a Lurgan, tal como había decidido.
Ahí me encontré con Robert Lodge, recién llegado de Inglaterra,
quien también tenía en su corazón ir a Londonderry.
Así, Robert Lodge y yo nos ocupamos de una obra y servicio, y viajamos juntos;
estábamos verdaderamente unidos en espíritu,
en la unidad de la fe y de la vida de Cristo.
En la bendita unidad y comunión del evangelio del Hijo de Dios,
trabajamos y viajamos por la nación de Irlanda durante doce meses,
separándonos con poca frecuencia (porque a veces fuimos movidos
a separarnos por un corto tiempo por el bien del servicio,
y luego nos reuníamos de nuevo).
El Señor nos dio dulce compañerismo y paz en todos nuestros viajes,
y no recuerdo que alguna vez nos enojáramos o entristeciéramos
uno al otro en todo ese tiempo.

Así pasamos nuestro tiempo, en diligente trabajo y duros viajes, a menudo con frío,
hambre y apuros en dicho país, el cual, para ese entonces,
estaba deshabitado en muchas partes.
Estuvimos en prisión varias veces, una vez en Armagh, una vez en Dublin,
dos veces en Cork;
además recibimos otros abusos de parte de muchos por causa de nuestro testimonio,
el cual teníamos que dar en nombre del Señor. Después de
viajar y trabajar juntos en el evangelio por doce meses,
y ver a muchos convencidos y llevados a la Verdad,
quedamos libres de nuestro servicio ahí y en el séptimo mes de 1660,
tomamos un barco en Carrickfergus hacia Inglaterra.

En casa regresé a mi vocación externa y me mantuve diligentemente asistiendo a las reuniones,
porque todavía me deleitaba hacerlo, y mientras estaba ahí,
era diligente esperando en el Señor. Pues siempre
encontré que ahí recibía de parte del Señor,
incremento de fuerza,
vida y sabiduría. Y cuando descubría algún movimiento del
Señor sobre mí para ir a cualquier reunión en el exterior,
en nuestro condado o en algún otro,
iba y descargaba lo que había en mi consciencia según el Señor me daba capacidad,
y luego regresaba a mi vocación externa, y así a nuestra propia reunión,
donde me deleitaba esperar en silencio en el Señor. Yo amaba mucho nuestras reuniones,
porque de ese modo encontraba un crecimiento interior a través
de las enseñanzas y revelaciones de Su Espíritu en mi corazón.
Y cuando algo era revelado en mí para decirlo en nuestra reunión,
me rendía a ello.
Y aunque algunas veces estaba cerca de apagar al Espíritu
por lentitud y temor de hablar en el nombre del Señor,
aun así crecía gradualmente y aumentaba en fe y confianza santa más y más.

[.small-break]
'''

+++[+++La siguiente epístola fue escrita mientras estaba en Irlanda,
y es una de muchas epístolas que pueden encontrarse en la versión no abreviaba
del Diario de la Vida y Trabajos del Evangelio de John Burnyeat]

[.embedded-content-document.letter]
--

[.salutation]
Queridos Amigos,

En cariñoso y tierno amor saludo a todos los fieles al Señor, sin acepción de personas.
En Su vida y amor los siento, en el cual mi corazón se abre para ustedes,
aquellos con quienes soy diariamente refrescado y consolado en Cristo Jesús,
fuente y manantial de vida y refrigerio.
En realidad, Él es nuestra Roca y diario refugio,
a quien huimos y somos salvados en el día de tormentas y tempestades,
cuando se levantan las inundaciones y las violentas olas del mar se encrespan y golpean.
Sin embargo, en la Luz tenemos un escondite seguro, y una segura y pacífica habitación,
contra La que estas no pueden prevalecer, mientras permanezcamos fieles al Señor en ella.
Su amor hacia nosotros ha abundado y abundará,
mientras permanezcamos en eso que Su amor alcanza, que es, Su propia Semilla.
Él ha levantado esta Semilla en nosotros por medio de Su poder y brazo extendido,
y en Ella los brotes de la vida y del amor son conocidos y recibidos.

¡Por lo tanto, mis queridos amigos, aférrense a ella y siéntanla continuamente!
Manténganse frescos, vivos y abiertos de corazón,
para que puedan estar siempre en la Vida,
y que nada que pueda cubrir la Semilla entre y la oprima.
Como uno que (con ustedes) ha sido hecho partícipe del rico e infinito amor de Dios,
los exhorto, amados, a seguir en Su amor y a permanecer fieles en la Vida,
para que la muerte no pase por encima de nadie otra vez.
Y más bien,
que la Vida que Dios ha levantado sea sentida y gobierne en cada uno de nosotros,
sobre el que tiene el poder de la muerte,
para alabanza y gloria de Aquel que nos ha redimido.
En Él, se recibe a diario todo consuelo, fuerza y refrigerio,
porque Él es la vida y la fuerza de todo el que espera en Él,
y está cerca para preservar a todo el que es recto
en su amor hacia Él. En Él tenemos seguridad,
creyendo que ni tribulación, aflicción, persecución,
angustia podrá separarnos del amor de Dios que disfrutamos en Cristo
Jesús. Y aunque el Señor permita que grandes dificultades vengan
sobre nosotros (como lo es en este día) para probarnos,
estas no pueden separarnos unos de otros,
ni quebrar nuestra unidad en el Espíritu en el que nos sentimos y gozamos unos con otros.

En esta unidad, mis queridos Amigos, los recuerdo con frecuencia,
para el gozo y alegría de mi corazón. Pues ciertamente
ustedes son a menudo mi gozo en el Señor,
cuando todos los demás consuelos me son quitados;
pero es por medio de esa Semilla en la que los siento y los disfruto,
en la que nuestra unidad, vida y amor permanecen, y en la que yo permanezco,

[.signed-section-closing]
Su hermano en mi medida recibida,

[.signed-section-signature]
John Burnyeat

[.signed-section-context-close]
Clanbrassil, Irlanda, el cuarto día del mes cuatro, de 1660

--

[.asterism]
'''

__Sería difícil exagerar la influencia que la vida y ministerio de
John Burnyeat tuvieron al principio de la Sociedad de Amigos.
Después de su muerte en 1690, George Fox escribió de él: "`Fue un amigo y hermano fiel,
y un ministro competente de Jesucristo... un verdadero apóstol de Jesucristo,
quien Lo predicó gratuitamente, tanto por mar como por tierra.
Fue un anciano y pilar en la casa de Dios,
y un hombre muy dotado de la sabiduría de Dios,
y en ella tenía cuidado del bienestar de la iglesia de Cristo.`"__

__Como muchos otros de los primeros trabajadores que el Señor envió a Su cosecha,
John Burnyeat viajó y ministró incesantemente,
predicando y animando al rebaño de Cristo por toda Inglaterra, Escocia, Irlanda,
Barbados y las colonias en América.
Fue encarcelado muchas veces por su testimonio,
y sufrió grandes injusticias a manos de sacerdotes y magistrados perseguidores.
Los últimos años de su vida los pasó en Irlanda,
donde fortaleció los corazones de los Amigos durante lo que ahora se llama '`La guerra
Guillermita,`' un tiempo de gran caos y derramamiento de sangre en la nación. Aquellos
que lo conocieron mejor lo describen como "`un instrumento precioso en la mano del Señor,
capaz y hábil en el ministerio para la consolación
de Su pueblo... un jovial alentador de ellos,
un querido amigo y verdadero hermano, un diligente obispo y tierno padre,
un hombre perfecto y recto en su día.`"__
